In [1]:
print("Ba Koko!")

Ba Koko!

In [8]:
import os
import pandas as pd

# Pfad zur Parquet-Datei im übergeordneten Ordner ../data
data_path = os.path.join("..", "data", "phoenix_anonymized.parquet")

# Daten einlesen
df = pd.read_parquet(data_path)

In [10]:
df.head()

,Unnamed: 0,DeviceId,IsControlSolutionDetected,MeasurementStatus,IsEmergencyTest,PatientId,ResultUnit,IsResultValueTooHigh,IsResultValueTooLow,StripId,...,InstrumentLotId,Location,PrivacyLevel,PatientID,Institution,Timestamp,TimeSinceLast,Region,GlucoseLevel,GlucoseValue
0,0,A101001231,False,NOT_RATED,False,jJHgdIcpnQHTwM08jD1w6oCiv8r+f1r4ZhLxIdDstXf+uh...,MMOL_PER_LITER,False,False,1401,...,5209211,Nuklearmedizin,3,b2fce9805d06,99b5f326c554,2024-08-20 10:02:10,NaN,Basel,normal,6.4
1,1,A101001282,False,NOT_RATED,False,nf4tBdCwGSjlN2UNcyrRXfVzxdEG3dxlZ2NYNKW3c9ChqX...,MMOL_PER_LITER,False,False,1404,...,5209211,UK Demo,3,e645772e5da3,55d1fd712fd0,2024-11-08 13:52:45,NaN,Other,normal,5.0
2,2,A101001282,False,NOT_RATED,False,nf4tBdCwGSjlN2UNcyrRXfVzxdEG3dxlZ2NYNKW3c9ChqX...,MMOL_PER_LITER,False,False,1403,...,5209211,UK Demo,3,e645772e5da3,55d1fd712fd0,2024-09-25 14:39:40,-3798785.0,Other,severe_hyper,13.4
3,3,A101001282,False,NOT_RATED,False,nf4tBdCwGSjlN2UNcyrRXfVzxdEG3dxlZ2NYNKW3c9ChqX...,MMOL_PER_LITER,False,False,1405,...,5209211,UK Demo,3,e645772e5da3,55d1fd712fd0,2024-09-13 10:42:11,-1051049.0,Other,severe_hyper,17.6
4,4,A101001286,False,NOT_RATED,False,1z9/QVfYDgJsrkRIy8J43zxvckyonbJk2uizzFKVpknR+p...,MMOL_PER_LITER,False,False,1401,...,5209211,Intensivstation,3,27a20bffa45c,99b5f326c554,2024-09-12 09:51:14,NaN,Basel,normal,6.3

In [11]:
df.describe()

,Unnamed: 0,StripId,InstrumentLotId,PrivacyLevel,Timestamp,TimeSinceLast,GlucoseValue
count,2.402642e+06,2.402642e+06,2.402642e+06,2.402642e+06,2402642,2.016591e+06,2.402642e+06
mean,1.201320e+06,1.591106e+03,5.255331e+06,2.999813e+00,2024-07-01 20:58:12.383372288,1.775979e+04,1.290769e+02
min,0.000000e+00,1.106000e+03,5.111262e+06,1.000000e+00,2021-10-12 21:13:06,-5.896059e+07,6.000000e-01
25%,6.006602e+05,1.558000e+03,5.211071e+06,3.000000e+00,2024-04-18 07:51:10.500000,-3.026806e+06,7.800000e+01
50%,1.201320e+06,1.654000e+03,5.211181e+06,3.000000e+00,2024-08-07 18:08:10,1.802000e+04,1.220000e+02
75%,1.801981e+06,1.675000e+03,5.304171e+06,3.000000e+00,2024-10-24 22:28:42.249999872,3.076595e+06,1.770000e+02
max,2.402641e+06,1.828000e+03,5.411111e+06,3.000000e+00,2025-02-28 22:29:22,7.053103e+07,6.000000e+02
std,6.935831e+05,1.340675e+02,7.801848e+04,1.372981e-02,NaN,4.424767e+06,9.192283e+01

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2402642 entries, 0 to 2402641
Data columns (total 21 columns):
 #   Column                     Dtype
---  ------                     -----
 0   Unnamed: 0                 int64
 1   DeviceId                   object
 2   IsControlSolutionDetected  bool
 3   MeasurementStatus          object
 4   IsEmergencyTest            bool
 5   PatientId                  object
 6   ResultUnit                 object
 7   IsResultValueTooHigh       bool
 8   IsResultValueTooLow        bool
 9   StripId                    int64
 10  ShipToAccountId            object
 11  InstrumentLotId            int64
 12  Location                   object
 13  PrivacyLevel               int64
 14  PatientID                  object
 15  Institution                object
 16  Timestamp                  datetime64[ns]
 17  TimeSinceLast              float64
 18  Region                     object
 19  GlucoseLevel               category
 20  GlucoseValue               float64
dtypes: bool(4), category(1), datetime64[ns](1), float64(2), int64(4), object(9)
memory usage: 304.7+ MB

In [13]:
df["PatientID"].value_counts().describe()

count    386051.000000
mean          6.223639
std          25.647652
min           1.000000
25%           1.000000
50%           1.000000
75%           3.000000
max        4921.000000
Name: count, dtype: float64

In [14]:
# Patienten mit mind. 6 Messungen
valid_patients = df["PatientID"].value_counts()
valid_patients = valid_patients[valid_patients >= 6].index

df_rnn = df[df["PatientID"].isin(valid_patients)].copy()

In [16]:
df_rnn.head()

,Unnamed: 0,DeviceId,IsControlSolutionDetected,MeasurementStatus,IsEmergencyTest,PatientId,ResultUnit,IsResultValueTooHigh,IsResultValueTooLow,StripId,...,InstrumentLotId,Location,PrivacyLevel,PatientID,Institution,Timestamp,TimeSinceLast,Region,GlucoseLevel,GlucoseValue
1,1,A101001282,False,NOT_RATED,False,nf4tBdCwGSjlN2UNcyrRXfVzxdEG3dxlZ2NYNKW3c9ChqX...,MMOL_PER_LITER,False,False,1404,...,5209211,UK Demo,3,e645772e5da3,55d1fd712fd0,2024-11-08 13:52:45,NaN,Other,normal,5.0
2,2,A101001282,False,NOT_RATED,False,nf4tBdCwGSjlN2UNcyrRXfVzxdEG3dxlZ2NYNKW3c9ChqX...,MMOL_PER_LITER,False,False,1403,...,5209211,UK Demo,3,e645772e5da3,55d1fd712fd0,2024-09-25 14:39:40,-3798785.0,Other,severe_hyper,13.4
3,3,A101001282,False,NOT_RATED,False,nf4tBdCwGSjlN2UNcyrRXfVzxdEG3dxlZ2NYNKW3c9ChqX...,MMOL_PER_LITER,False,False,1405,...,5209211,UK Demo,3,e645772e5da3,55d1fd712fd0,2024-09-13 10:42:11,-1051049.0,Other,severe_hyper,17.6
5,5,A101001286,False,NOT_RATED,False,BIr2Iq66c8+qykriWxoEWZOb7gH2ULb/8VxEOzqCajHJpG...,MMOL_PER_LITER,False,False,1401,...,5209211,Intensivstation,3,55362000d513,99b5f326c554,2024-08-23 14:41:52,NaN,Basel,normal,7.0
6,6,A101001286,False,NOT_RATED,False,BIr2Iq66c8+qykriWxoEWZOb7gH2ULb/8VxEOzqCajHJpG...,MMOL_PER_LITER,False,False,1401,...,5209211,Intensivstation,3,55362000d513,99b5f326c554,2024-10-19 08:37:50,4902958.0,Basel,hyper,8.0